steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'setup'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        mkdir -p output
        mkdir -p output/web
        cp -r etl/dadguide_proto output/
        cp -r etl/pad output/
        cp -r web/data output/
        cp web/admin_api_server.py output/
        cp web/requirements.txt output/
        cp web/Dockerfile output/

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'download-db-config'
    entrypoint: 'bash'
    args: [ '-c', 'gcloud secrets versions access latest --secret=prod_db_config > output/db_config.json' ]

  - name: 'gcr.io/cloud-builders/docker'
    dir: 'output'
    args: [
      'build',
      '--build-arg', 'SCRIPT_NAME=admin_api_server.py',
      '--build-arg', 'EXTRA_ARG=--web_dir=/server/web',
      '-t', 'gcr.io/$PROJECT_ID/admin-api-server',
      '.'
    ]

images: ['gcr.io/$PROJECT_ID/admin-api-server']
