# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: enemy_skills.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='enemy_skills.proto',
  package='dadguide_proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12\x65nemy_skills.proto\x12\x0e\x64\x61\x64guide_proto\"@\n\x0fMonsterBehavior\x12-\n\x06groups\x18\x01 \x03(\x0b\x32\x1d.dadguide_proto.BehaviorGroup\"\xb2\x02\n\rBehaviorGroup\x12;\n\ngroup_type\x18\x01 \x01(\x0e\x32\'.dadguide_proto.BehaviorGroup.GroupType\x12,\n\tcondition\x18\x02 \x01(\x0b\x32\x19.dadguide_proto.Condition\x12.\n\x08\x63hildren\x18\x03 \x03(\x0b\x32\x1c.dadguide_proto.BehaviorItem\"\x85\x01\n\tGroupType\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x0b\n\x07PASSIVE\x10\x01\x12\x0b\n\x07PREEMPT\x10\x02\x12\x11\n\rDISPEL_PLAYER\x10\x03\x12\x12\n\x0eMONSTER_STATUS\x10\x04\x12\r\n\tREMAINING\x10\x05\x12\x0c\n\x08STANDARD\x10\x06\x12\t\n\x05\x44\x45\x41TH\x10\x07\"u\n\x0c\x42\x65haviorItem\x12.\n\x05group\x18\x02 \x01(\x0b\x32\x1d.dadguide_proto.BehaviorGroupH\x00\x12,\n\x08\x62\x65havior\x18\x03 \x01(\x0b\x32\x18.dadguide_proto.BehaviorH\x00\x42\x07\n\x05value\"P\n\x08\x42\x65havior\x12,\n\tcondition\x18\x01 \x01(\x0b\x32\x19.dadguide_proto.Condition\x12\x16\n\x0e\x65nemy_skill_id\x18\x02 \x01(\x05\"\xc1\x01\n\tCondition\x12\x14\n\x0chp_threshold\x18\x01 \x01(\x05\x12\x12\n\nuse_chance\x18\x02 \x01(\x05\x12\x15\n\rrepeats_every\x18\x03 \x01(\x05\x12\x17\n\x0fglobal_one_time\x18\x08 \x01(\x08\x12\x19\n\x11\x65nemies_remaining\x18\x04 \x01(\x05\x12\x10\n\x08on_death\x18\x05 \x01(\x08\x12\x13\n\x0borb_limited\x18\x06 \x01(\x08\x12\x18\n\x10trigger_monsters\x18\x07 \x03(\x05\x62\x06proto3')
)



_BEHAVIORGROUP_GROUPTYPE = _descriptor.EnumDescriptor(
  name='GroupType',
  full_name='dadguide_proto.BehaviorGroup.GroupType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PASSIVE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PREEMPT', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DISPEL_PLAYER', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MONSTER_STATUS', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REMAINING', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STANDARD', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DEATH', index=7, number=7,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=278,
  serialized_end=411,
)
_sym_db.RegisterEnumDescriptor(_BEHAVIORGROUP_GROUPTYPE)


_MONSTERBEHAVIOR = _descriptor.Descriptor(
  name='MonsterBehavior',
  full_name='dadguide_proto.MonsterBehavior',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='groups', full_name='dadguide_proto.MonsterBehavior.groups', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=102,
)


_BEHAVIORGROUP = _descriptor.Descriptor(
  name='BehaviorGroup',
  full_name='dadguide_proto.BehaviorGroup',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='group_type', full_name='dadguide_proto.BehaviorGroup.group_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='condition', full_name='dadguide_proto.BehaviorGroup.condition', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='children', full_name='dadguide_proto.BehaviorGroup.children', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _BEHAVIORGROUP_GROUPTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=411,
)


_BEHAVIORITEM = _descriptor.Descriptor(
  name='BehaviorItem',
  full_name='dadguide_proto.BehaviorItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='group', full_name='dadguide_proto.BehaviorItem.group', index=0,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='behavior', full_name='dadguide_proto.BehaviorItem.behavior', index=1,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='value', full_name='dadguide_proto.BehaviorItem.value',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=413,
  serialized_end=530,
)


_BEHAVIOR = _descriptor.Descriptor(
  name='Behavior',
  full_name='dadguide_proto.Behavior',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='condition', full_name='dadguide_proto.Behavior.condition', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enemy_skill_id', full_name='dadguide_proto.Behavior.enemy_skill_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=532,
  serialized_end=612,
)


_CONDITION = _descriptor.Descriptor(
  name='Condition',
  full_name='dadguide_proto.Condition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hp_threshold', full_name='dadguide_proto.Condition.hp_threshold', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='use_chance', full_name='dadguide_proto.Condition.use_chance', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='repeats_every', full_name='dadguide_proto.Condition.repeats_every', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='global_one_time', full_name='dadguide_proto.Condition.global_one_time', index=3,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enemies_remaining', full_name='dadguide_proto.Condition.enemies_remaining', index=4,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='on_death', full_name='dadguide_proto.Condition.on_death', index=5,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orb_limited', full_name='dadguide_proto.Condition.orb_limited', index=6,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trigger_monsters', full_name='dadguide_proto.Condition.trigger_monsters', index=7,
      number=7, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=615,
  serialized_end=808,
)

_MONSTERBEHAVIOR.fields_by_name['groups'].message_type = _BEHAVIORGROUP
_BEHAVIORGROUP.fields_by_name['group_type'].enum_type = _BEHAVIORGROUP_GROUPTYPE
_BEHAVIORGROUP.fields_by_name['condition'].message_type = _CONDITION
_BEHAVIORGROUP.fields_by_name['children'].message_type = _BEHAVIORITEM
_BEHAVIORGROUP_GROUPTYPE.containing_type = _BEHAVIORGROUP
_BEHAVIORITEM.fields_by_name['group'].message_type = _BEHAVIORGROUP
_BEHAVIORITEM.fields_by_name['behavior'].message_type = _BEHAVIOR
_BEHAVIORITEM.oneofs_by_name['value'].fields.append(
  _BEHAVIORITEM.fields_by_name['group'])
_BEHAVIORITEM.fields_by_name['group'].containing_oneof = _BEHAVIORITEM.oneofs_by_name['value']
_BEHAVIORITEM.oneofs_by_name['value'].fields.append(
  _BEHAVIORITEM.fields_by_name['behavior'])
_BEHAVIORITEM.fields_by_name['behavior'].containing_oneof = _BEHAVIORITEM.oneofs_by_name['value']
_BEHAVIOR.fields_by_name['condition'].message_type = _CONDITION
DESCRIPTOR.message_types_by_name['MonsterBehavior'] = _MONSTERBEHAVIOR
DESCRIPTOR.message_types_by_name['BehaviorGroup'] = _BEHAVIORGROUP
DESCRIPTOR.message_types_by_name['BehaviorItem'] = _BEHAVIORITEM
DESCRIPTOR.message_types_by_name['Behavior'] = _BEHAVIOR
DESCRIPTOR.message_types_by_name['Condition'] = _CONDITION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MonsterBehavior = _reflection.GeneratedProtocolMessageType('MonsterBehavior', (_message.Message,), {
  'DESCRIPTOR' : _MONSTERBEHAVIOR,
  '__module__' : 'enemy_skills_pb2'
  # @@protoc_insertion_point(class_scope:dadguide_proto.MonsterBehavior)
  })
_sym_db.RegisterMessage(MonsterBehavior)

BehaviorGroup = _reflection.GeneratedProtocolMessageType('BehaviorGroup', (_message.Message,), {
  'DESCRIPTOR' : _BEHAVIORGROUP,
  '__module__' : 'enemy_skills_pb2'
  # @@protoc_insertion_point(class_scope:dadguide_proto.BehaviorGroup)
  })
_sym_db.RegisterMessage(BehaviorGroup)

BehaviorItem = _reflection.GeneratedProtocolMessageType('BehaviorItem', (_message.Message,), {
  'DESCRIPTOR' : _BEHAVIORITEM,
  '__module__' : 'enemy_skills_pb2'
  # @@protoc_insertion_point(class_scope:dadguide_proto.BehaviorItem)
  })
_sym_db.RegisterMessage(BehaviorItem)

Behavior = _reflection.GeneratedProtocolMessageType('Behavior', (_message.Message,), {
  'DESCRIPTOR' : _BEHAVIOR,
  '__module__' : 'enemy_skills_pb2'
  # @@protoc_insertion_point(class_scope:dadguide_proto.Behavior)
  })
_sym_db.RegisterMessage(Behavior)

Condition = _reflection.GeneratedProtocolMessageType('Condition', (_message.Message,), {
  'DESCRIPTOR' : _CONDITION,
  '__module__' : 'enemy_skills_pb2'
  # @@protoc_insertion_point(class_scope:dadguide_proto.Condition)
  })
_sym_db.RegisterMessage(Condition)


# @@protoc_insertion_point(module_scope)
