version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'dadguide'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # Change this if you have a conflict, but you may have to change other stuff as well.
      - '3306:3306'
    expose:
      - 3306
    volumes:
      - dadguide-db:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'

volumes:
  dadguide-db:
